<?php

/**
 * @file
 * Contains menu_block.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function menu_block_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the menu_block module.
    case 'help.page.menu_block':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Create blocks that contain one or more levels of a menu') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function menu_block_theme() {
  $theme = [];

  return $theme;
}
